version: '3.8'

networks:
  lakehouse-net:
    driver: bridge

services:
  # service1: minio
  minio:
    image: minio/minio
    container_name: lakehouse-minio
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - lakehouse-net
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data_lake:/data
    command: server /data --console-address ":9001"

  # service2: postges
  postgres:
    image: postgres:13
    container_name: lakehouse-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - lakehouse-net

  # service3: dagster-webserver
  dagster-webserver:
    build: ./Dagster_home
    container_name: lakehouse-dagster-webserver
    ports:
      - "3000:3000"
    networks:
      - lakehouse-net
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      PYTHONPATH: /opt/dagster/app:/opt/dagster/etl # <--- THÊM DÒNG NÀY: Chỉ đường cho Python
      TZ: Asia/Ho_Chi_Minh
      SPARK_EXTRA_JARS: /opt/dagster/jars/delta-spark_2.12-3.2.0.jar,/opt/dagster/jars/delta-storage-3.2.0.jar,/opt/dagster/jars/hadoop-aws-3.3.4.jar,/opt/dagster/jars/aws-java-sdk-bundle-1.12.262.jar
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_DRIVER_HOST: dagster-webserver
      SPARK_DRIVER_BIND_ADDRESS: 0.0.0.0
    env_file:
      - .env
    volumes:
      - ./Dagster_home:/opt/dagster/app
      - ./Dagster_home/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./etl:/opt/dagster/etl # <--- THÊM DÒNG NÀY: Mount thư mục etl vào container
      - ./etl_pipeline:/opt/dagster/app/etl_pipeline # <--- THÊM DÒNG NÀY: Mount package etl_pipeline
    depends_on:
      - postgres
      - spark-master
    command: dagster-webserver -h 0.0.0.0 -p 3000

  # service4: dagster-daemon
  dagster-daemon:
    build: ./Dagster_home
    container_name: lakehouse-dagster-daemon
    networks:
      - lakehouse-net
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      PYTHONPATH: /opt/dagster/app:/opt/dagster/etl # <--- THÊM DÒNG NÀY
      TZ: Asia/Ho_Chi_Minh
      SPARK_EXTRA_JARS: /opt/dagster/jars/delta-spark_2.12-3.2.0.jar,/opt/dagster/jars/delta-storage-3.2.0.jar,/opt/dagster/jars/hadoop-aws-3.3.4.jar,/opt/dagster/jars/aws-java-sdk-bundle-1.12.262.jar
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_DRIVER_HOST: dagster-daemon
      SPARK_DRIVER_BIND_ADDRESS: 0.0.0.0
    env_file:
      - .env
    volumes:
      - ./Dagster_home:/opt/dagster/app
      - ./Dagster_home/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - ./etl:/opt/dagster/etl # <--- THÊM DÒNG NÀY
      - ./etl_pipeline:/opt/dagster/app/etl_pipeline # <--- THÊM DÒNG NÀY
    depends_on:
      - postgres
      - spark-master
    command: dagster-daemon run

  # service5: spark-master
  spark-master:
    build: ./spark
    image: lakehouse-spark:3.5.1-py310
    container_name: lakehouse-spark-master
    networks:
      - lakehouse-net
    environment:
      - PYSPARK_PYTHON=/opt/pyenv/shims/python
      - PYSPARK_DRIVER_PYTHON=/opt/pyenv/shims/python
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"

  # service6: spark-worker
  spark-worker:
    build: ./spark
    image: lakehouse-spark:3.5.1-py310
    container_name: lakehouse-spark-worker
    networks:
      - lakehouse-net
    environment:
      - PYSPARK_PYTHON=/opt/pyenv/shims/python
      - PYSPARK_DRIVER_PYTHON=/opt/pyenv/shims/python
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
    depends_on:
      - spark-master

  # service7: spark-thrift-server
  spark-thrift:
    image: lakehouse-spark:3.5.1-py310
    container_name: lakehouse-spark-thrift
    networks:
      - lakehouse-net
    env_file:
      - .env
    environment:
      - PYSPARK_PYTHON=/opt/pyenv/shims/python
      - PYSPARK_DRIVER_PYTHON=/opt/pyenv/shims/python
    command:
      - /bin/bash
      - -lc
      - >
        /opt/spark/sbin/start-thriftserver.sh
        --master spark://spark-master:7077
        --name "Spark Thrift Server"
        --packages io.delta:delta-core_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
        --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
        --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
        --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
        --conf spark.hadoop.fs.s3a.access.key=${MINIO_ROOT_USER}
        --conf spark.hadoop.fs.s3a.secret.key=${MINIO_ROOT_PASSWORD}
        --conf spark.hadoop.fs.s3a.path.style.access=true
        --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false
        --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
        --conf spark.sql.warehouse.dir=s3a://gold-lake/warehouse
        && tail -f /opt/spark/logs/*thriftserver*.out
    ports:
      - "10000:10000"
    depends_on:
      - spark-master

  # service8: superset
  superset:
    build: ./superset
    container_name: lakehouse-superset
    ports:
      - "8088:8088"
    networks:
      - lakehouse-net
    environment:
      SUPERSET_SECRET_KEY: "change_me_to_a_secure_random_string"
      SUPERSET_ADMIN_USER: "admin"
      SUPERSET_ADMIN_PASSWORD: "admin123"
      SUPERSET_ADMIN_EMAIL: "admin@example.com"
      SUPERSET_HOME: /app/superset_home
      SUPERSET_LOAD_EXAMPLES: "no"
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./superset/init.sh:/app/init.sh
      - ./superset_home:/app/superset_home
    depends_on:
      - spark-thrift
    command: ["/bin/bash", "/app/init.sh"]
